name: denoise
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # Make sure this matches your system's CUDA driver version
  - hydra-core
  - omegaconf
  - tqdm
  - nltk
  - datasets
  - lightning
  - pip
  - pip:
    - sentence-transformers
    # - rouge-score
    - wandb